# Generated by Django 2.1.2 on 2019-02-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='主机名')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP地址')),
                ('port', models.IntegerField(blank=True, default=6800, null=True, verbose_name='端口')),
                ('description', models.TextField(blank=True, null=True, verbose_name='主机描述')),
                ('auth', models.IntegerField(blank=True, default=0, null=True, verbose_name='认证')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='主机用户名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
    ]
