# Generated by Django 2.1.2 on 2019-02-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
    ]
