# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloveinfo',
            name='love_type',
            field=models.IntegerField(choices=[(1, '收藏机构'), (2, '收藏课程'), (3, '收藏讲师')], verbose_name='收藏类别'),
        ),
    ]
