# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartinfo',
            name='is_select',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u9009\u4e2d'),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='number',
            field=models.IntegerField(default=0, verbose_name='\u8d2d\u4e70\u6570\u91cf'),
        ),
    ]
