# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180804_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='trade_no',
            new_name='trade_sn',
        ),
    ]
