# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-14 19:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_auto_20180814_1032'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love_status', models.BooleanField(default=False, verbose_name='关注状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='关注时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ProjectInfo', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属收藏人')),
            ],
            options={
                'verbose_name': '用户关注',
                'verbose_name_plural': '用户关注',
            },
        ),
    ]
