# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 19:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0004_goods_goods_click'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u5546\u54c1\u5355\u4ef7')),
                ('count', models.IntegerField(default=1, verbose_name='\u6240\u4e70\u6570\u91cf')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='\u6240\u5c5e\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u8be6\u60c5',
                'verbose_name_plural': '\u8ba2\u5355\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, verbose_name='\u8ba2\u5355\u53f7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_pay', models.BooleanField(default=False, verbose_name='\u662f\u5426\u652f\u4ed8')),
                ('totle', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u8ba2\u5355\u603b\u4ef7')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u4fe1\u606f',
                'verbose_name_plural': '\u8ba2\u5355\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderInfo', verbose_name='\u6240\u5c5e\u8ba2\u5355'),
        ),
    ]
