# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '科技'), (2, '设计'), (3, '公益'), (4, '农业')], default=1, verbose_name='众筹类型')),
                ('name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('brief', models.CharField(max_length=50, verbose_name='简介')),
                ('target_amount', models.FloatField(verbose_name='筹资金额')),
                ('curr_amount', models.FloatField(default=0, verbose_name='已筹金额')),
                ('curr_support', models.IntegerField(default=0, verbose_name='支持人数')),
                ('days_num', models.IntegerField(default=30, verbose_name='筹资天数')),
                ('dead_line', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('status', models.IntegerField(choices=[(1, '众筹中'), (2, '众筹成功'), (3, '众筹失败')], default=1, verbose_name='状态')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('front_image', models.ImageField(upload_to='fundings/%y/%m', verbose_name='项目头图')),
                ('detail_image', models.ImageField(upload_to='fundings/%y/%m', verbose_name='项目详情（图）')),
                ('sponser_brief', models.CharField(max_length=40, verbose_name='自我介绍')),
                ('sponser_desc', models.CharField(max_length=160, verbose_name='详细自我介绍')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('service_tel', models.CharField(max_length=11, verbose_name='客服电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('alipay_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='企业账户')),
                ('legal_person', models.CharField(blank=True, max_length=18, null=True, verbose_name='法人身份证号码')),
            ],
            options={
                'verbose_name': '众筹信息',
                'verbose_name_plural': '众筹信息',
            },
        ),
        migrations.CreateModel(
            name='PayBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '实物回报'), (2, '虚拟物品回报')], default=1, verbose_name='回报类型')),
                ('payment', models.FloatField(verbose_name='支付金额')),
                ('payback_content', models.CharField(max_length=200, verbose_name='回报内容')),
                ('image', models.ImageField(upload_to='fundings/%y/%m', verbose_name='说明图片')),
                ('payback_num', models.IntegerField(default=0, verbose_name='回报数量')),
                ('limitation', models.IntegerField(default=0, verbose_name='单笔限购')),
                ('freight', models.FloatField(default=0, verbose_name='运费')),
                ('invoice', models.BooleanField(default=False, verbose_name='可否开发票')),
                ('payback_time', models.IntegerField(verbose_name='回报时间')),
                ('support_num', models.IntegerField(default=0, verbose_name='支持人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Funding', verbose_name='众筹项目')),
            ],
            options={
                'verbose_name': '回报信息',
                'verbose_name_plural': '回报信息',
            },
        ),
    ]
