# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20171210_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goos_unit',
            new_name='goods_unit',
        ),
    ]
