# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20171210_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_click',
            field=models.IntegerField(default=0, verbose_name='\u5546\u54c1\u70ed\u5ea6'),
        ),
    ]
