"""
Django settings for CrowdFunding project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os, sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))
sys.path.insert(0, os.path.join(BASE_DIR, "extra_apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nukrlm@!q*ahvz+g0#(a-nd#q22=4s^-q=0o9j0=+icfx(veap'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UserConfig',
    'items.apps.ItemsConfig',
    'operations.apps.OperationsConfig',
    'DjangoUeditor',
    'xadmin',
    'crispy_forms',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'CrowdFunding.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'CrowdFunding.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用mysql
        'NAME': 'tom',  # 数据库名称
        'USER': 'root',  # 连接数据库的账号
        'PASSWORD': 'mysql',  # 连接数据库的密码
        'HOST': '127.0.0.1',  # 或者localhost，主机
        'PORT': 3306,  # 端口

    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
# 配置静态资源路径
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

# 配置media的url

MEDIA_URL = '/static/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media')
# 指定用户
AUTH_USER_MODEL = 'users.UserProfile'
# 邮箱验证
# 1 qq 邮箱
# EMAIL_HOST = 'smtp.qq.com'
# EMAIL_HOST_USER = '289237642@qq.com'
# EMAIL_HOST_PASSWORD = 'tqdoeceqzeepcbdg'
# EMAIL_PORT = 587
# EMAIL_FROM = '289237642@qq.com'
# EMAIL_USE_TLS = True

# 2 新浪 邮箱
EMAIL_HOST = 'smtp.sina.cn'
EMAIL_HOST_USER = '15769202654@sina.cn'
EMAIL_HOST_PASSWORD = '289237642'
EMAIL_PORT = 25
EMAIL_FORM = '15769202654@sina.cn'
EMAIL_USE_TLS = True

# 163邮箱
# EMAIL_HOST = 'smtp.163.com'
# EMAIL_PORT = 25
# EMAIL_HOST_USER = 'a289237642@163.com'
# EMAIL_HOST_PASSWORD = 'a289237642'
# EMAIL_FROM = 'a289237642@163.com'
