# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='', verbose_name='轮播图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图信息',
                'verbose_name_plural': '轮播图信息',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='收藏状态')),
            ],
            options={
                'verbose_name': '用户收藏信息',
                'verbose_name_plural': '用户收藏信息',
            },
        ),
        migrations.CreateModel(
            name='UserSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1, verbose_name='支持数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('order_amount', models.FloatField(default=0, verbose_name='订单金额')),
                ('success', models.BooleanField(default=False, verbose_name='支付成功')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, verbose_name='订单号码')),
                ('trade_sn', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易编号')),
                ('signer_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='签收人')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='签收地址')),
                ('signer_mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='签收电话')),
                ('message', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('invoice_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='发票抬头')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('payback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.PayBack', verbose_name='回报')),
            ],
            options={
                'verbose_name': '用户支持信息',
                'verbose_name_plural': '用户支持信息',
            },
        ),
    ]
