# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginfo',
            name='category',
            field=models.CharField(blank=True, choices=[('jg', '机构'), ('gx', '高校'), ('gr', '个人')], max_length=5, null=True, verbose_name='机构类别'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='course_num',
            field=models.IntegerField(default=0, verbose_name='课程数量'),
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='address',
            field=models.CharField(max_length=200, verbose_name='机构地址'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='desc',
            field=models.CharField(max_length=200, verbose_name='机构简介'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='teacher/%y/%m', verbose_name='讲师头像'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='work_company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='就职公司'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='work_position',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='工作职位'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='work_style',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='教学特点'),
        ),
    ]
