"""
Django settings for lg project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))
sys.path.insert(0, os.path.join(BASE_DIR, "extra_apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pgw1j$wc9l#v2ghoyh^gne8gbz)z^q2bykbp7hu2q_yd#fs5vf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# 替换系统的用户
AUTH_USER_MODEL = "users.UserProfile"

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DjangoUeditor',  # 富文本
    'xadmin',
    'crispy_forms',
    'users.apps.UsersConfig',
    'goods.apps.GoodsConfig',
    'trade.apps.TradeConfig',
    'user_operation.apps.UserOperationConfig',
    'rest_framework',
    'django_filters',  # 过滤器
    'corsheaders',  # 支持跨域请求
    'rest_framework.authtoken',  # TokenAuthentication认证的配置
    'social_django',  # 微博第三方登录
    'raven.contrib.django.raven_compat',  # 手机错误日志的库
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 跨域的中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 允许跨域请求
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'lg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 第三方登录
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'lg.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用mysql
        'NAME': 'lg',  # 数据库名称
        'USER': 'root',  # 连接数据库的账号
        'PASSWORD': 'mysql',  # 连接数据库的密码
        'HOST': '127.0.0.1',  # 或者localhost，主机
        # 'HOST':'192.168.77.128 ',
        'PORT': 3306,  # 端口

    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
# 配置静态资源路径
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

# 配置media的url
MEDIA_URL = "/media/"
# 加入到环境变量
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 以后REST_FRAMEWORK的配置都在这里
REST_FRAMEWORK = {
    # rest_framework目录下的pagination.py文件PageNumberPagination类
    # 'DEFAULT_PAGINATION_CLASS': "rest_framework.pagination.PageNumberPagination",
    # 每页显示10条数据
    # 'PAGE_SIZE': 10,
    # 'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),

    # 'DEFAULT_THROTTLE_CLASSES': (
    #     # 用户未登录，根据ip地址判断
    #     'rest_framework.throttling.AnonRateThrottle',
    #     # 用户登录，通过token判断也就是Session判断,用户登录后也要限制
    #     'rest_framework.throttling.UserRateThrottle'
    # ),
    # 'DEFAULT_THROTTLE_RATES': {
    #     # 具体设置多少，根据网站的运营情况
    #     # 'anon': '100/day',
    #     # 'user': '1000/day',
    #     'anon': '2/minute',
    #     'user': '3/minute'
    # },

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    )
}
# 配置用户登录后台验证
# AUTHENTICATION_BACKENDS = (
#     'users.views.CustomModelBackend',
# )
# 配置用户登录后台验证
AUTHENTICATION_BACKENDS = (
    'users.views.CustomModelBackend',
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.weibo.WeiboOAuth2',  # 微博登陆认证
    # 'social_core.backends.qq.QQOAuth2',  # QQ登录认证
    # 'social_core.backends.weixin.WeixinOAuth2',  # 微信登录认证
)

# 微博
SOCIAL_AUTH_WEIBO_KEY = '766303709'
SOCIAL_AUTH_WEIBO_SECRET = 'a5dd2411328c23df34a1bc4d22b99524'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/index/'

import datetime

JWT_AUTH = {
    # 设置过期日期
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
    # 设置认证前缀
    'JWT_AUTH_HEADER_PREFIX': 'JWT',
}

# 手机号码的正则表达式
REGEX_MOBILE = "^1[345678]\d{9}$"
# 支付宝相关配置
# 应用私钥
private_key_path = os.path.join(BASE_DIR, "apps/trade/keys/private_2048.txt")
# 支付宝公钥
ali_public_path = os.path.join(BASE_DIR, "apps/trade/keys/alipay_key_2048.txt")

# 配置drf-extensions缓存超时
REST_FRAMEWORK_EXTENSIONS = {
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': 15 * 60
}

# django-redis缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 配置sentry发送错误日志到服务器上
RAVEN_CONFIG = {
    'dsn': 'http://d15887e30b5b484ebf73ca30f6b61c5e:bad3446ce56e42a2b30fd959ef5b94c2@118.190.202.67:9000/3',
}
