# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentinfo',
            name='comment_content',
            field=models.CharField(max_length=200, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='userloveinfo',
            name='love_id',
            field=models.IntegerField(verbose_name='收藏id'),
        ),
        migrations.AlterField(
            model_name='usermessageinfo',
            name='message',
            field=models.CharField(max_length=200, verbose_name='消息内容'),
        ),
    ]
