# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180621_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='need_know',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='teacher_say',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='老师告知'),
        ),
    ]
