# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-14 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatgoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
            },
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/%y/%m', verbose_name='项目图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '项目图片',
                'verbose_name_plural': '项目图片',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='项目标题')),
                ('desc', models.CharField(max_length=200, verbose_name='项目简介')),
                ('love_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project/%y/%m', verbose_name='项目图片详情')),
                ('nums', models.IntegerField(default=0, verbose_name='关注人数')),
                ('status', models.CharField(choices=[('即将开始', '即将开始'), ('众筹中', '众筹中'), ('众筹成功', '众筹成功')], max_length=10, verbose_name='状态')),
                ('money_total', models.FloatField(default=0.0, verbose_name='目标金额')),
                ('money_ing', models.FloatField(default=0.0, verbose_name='已筹金额')),
                ('days', models.IntegerField(default=30, verbose_name='众筹总天数')),
                ('is_status', models.CharField(choices=[('未支持', '未支持'), ('支持', '支持')], default='0', max_length=10, verbose_name='支持状态')),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='截止日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('categoryinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.CatgoryInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
    ]
