# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-14 08:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='projectInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属人'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='projectInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ProjectInfo', verbose_name='所属项目'),
        ),
    ]
